2025-01-03T18:09:23.843267+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=a5026a0a-91fd-40fe-9ae1-b18e8b1b9eb1 fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:09:23.992119+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=9d2c219e-6757-4962-bc11-22d14d0b812c fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:09:29.087120+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=13b08640-95eb-4d6d-ae63-59465c2a360c fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:09:29.304206+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=cea7abaa-2060-473b-be29-26dcc4f68121 fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:09:30.153692+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=5fc09ea3-82ba-405b-9f45-1a3b08aa1046 fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:18:27.243683+00:00 heroku[web.1]: Starting process with command `gunicorn PersonalWebsite.wsgi:application --log-file -`
2025-01-03T18:18:27.781393+00:00 app[web.1]: Python buildpack: Detected 512 MB available memory and 8 CPU cores.
2025-01-03T18:18:27.781481+00:00 app[web.1]: Python buildpack: Defaulting WEB_CONCURRENCY to 2 based on the available memory.
2025-01-03T18:18:28.076871+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [2] [INFO] Starting gunicorn 20.1.0
2025-01-03T18:18:28.077182+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [2] [INFO] Listening at: http://0.0.0.0:20732 (2)
2025-01-03T18:18:28.077210+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [2] [INFO] Using worker: sync
2025-01-03T18:18:28.079396+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [9] [INFO] Booting worker with pid: 9
2025-01-03T18:18:28.083329+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [9] [ERROR] Exception in worker process
2025-01-03T18:18:28.083336+00:00 app[web.1]: Traceback (most recent call last):
2025-01-03T18:18:28.083337+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2025-01-03T18:18:28.083341+00:00 app[web.1]: worker.init_process()
2025-01-03T18:18:28.083341+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~^^
2025-01-03T18:18:28.083341+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 134, in init_process
2025-01-03T18:18:28.083342+00:00 app[web.1]: self.load_wsgi()
2025-01-03T18:18:28.083343+00:00 app[web.1]: ~~~~~~~~~~~~~~^^
2025-01-03T18:18:28.083343+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2025-01-03T18:18:28.083343+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2025-01-03T18:18:28.083343+00:00 app[web.1]: ~~~~~~~~~~~~~^^
2025-01-03T18:18:28.083343+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-01-03T18:18:28.083344+00:00 app[web.1]: self.callable = self.load()
2025-01-03T18:18:28.083344+00:00 app[web.1]: ~~~~~~~~~^^
2025-01-03T18:18:28.083344+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-01-03T18:18:28.083345+00:00 app[web.1]: return self.load_wsgiapp()
2025-01-03T18:18:28.083345+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-01-03T18:18:28.083345+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-01-03T18:18:28.083345+00:00 app[web.1]: return util.import_app(self.app_uri)
2025-01-03T18:18:28.083345+00:00 app[web.1]: ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-01-03T18:18:28.083345+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/util.py", line 359, in import_app
2025-01-03T18:18:28.083345+00:00 app[web.1]: mod = importlib.import_module(module)
2025-01-03T18:18:28.083346+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-01-03T18:18:28.083346+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-01-03T18:18:28.083346+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-03T18:18:28.083347+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-01-03T18:18:28.083347+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-01-03T18:18:28.083347+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
2025-01-03T18:18:28.083347+00:00 app[web.1]: ModuleNotFoundError: No module named 'PersonalWebsite.wsgi'
2025-01-03T18:18:28.083386+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [9] [INFO] Worker exiting (pid: 9)
2025-01-03T18:18:28.112110+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [2] [INFO] Shutting down: Master
2025-01-03T18:18:28.112141+00:00 app[web.1]: [2025-01-03 18:18:28 +0000] [2] [INFO] Reason: Worker failed to boot.
2025-01-03T18:18:28.176173+00:00 heroku[web.1]: Process exited with status 3
2025-01-03T18:18:28.194361+00:00 heroku[web.1]: State changed from starting to crashed
2025-01-03T18:18:28.196873+00:00 heroku[web.1]: State changed from crashed to starting
2025-01-03T18:18:32.658036+00:00 heroku[web.1]: Starting process with command `gunicorn PersonalWebsite.wsgi:application --log-file -`
2025-01-03T18:18:33.189683+00:00 app[web.1]: Python buildpack: Detected 512 MB available memory and 8 CPU cores.
2025-01-03T18:18:33.189708+00:00 app[web.1]: Python buildpack: Defaulting WEB_CONCURRENCY to 2 based on the available memory.
2025-01-03T18:18:33.481717+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [2] [INFO] Starting gunicorn 20.1.0
2025-01-03T18:18:33.482007+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [2] [INFO] Listening at: http://0.0.0.0:10852 (2)
2025-01-03T18:18:33.482043+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [2] [INFO] Using worker: sync
2025-01-03T18:18:33.484123+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [9] [INFO] Booting worker with pid: 9
2025-01-03T18:18:33.488179+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [9] [ERROR] Exception in worker process
2025-01-03T18:18:33.488180+00:00 app[web.1]: Traceback (most recent call last):
2025-01-03T18:18:33.488181+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2025-01-03T18:18:33.488182+00:00 app[web.1]: worker.init_process()
2025-01-03T18:18:33.488182+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~^^
2025-01-03T18:18:33.488182+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 134, in init_process
2025-01-03T18:18:33.488182+00:00 app[web.1]: self.load_wsgi()
2025-01-03T18:18:33.488183+00:00 app[web.1]: ~~~~~~~~~~~~~~^^
2025-01-03T18:18:33.488183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2025-01-03T18:18:33.488183+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2025-01-03T18:18:33.488183+00:00 app[web.1]: ~~~~~~~~~~~~~^^
2025-01-03T18:18:33.488183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-01-03T18:18:33.488184+00:00 app[web.1]: self.callable = self.load()
2025-01-03T18:18:33.488184+00:00 app[web.1]: ~~~~~~~~~^^
2025-01-03T18:18:33.488184+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-01-03T18:18:33.488184+00:00 app[web.1]: return self.load_wsgiapp()
2025-01-03T18:18:33.488184+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~^^
2025-01-03T18:18:33.488184+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-01-03T18:18:33.488185+00:00 app[web.1]: return util.import_app(self.app_uri)
2025-01-03T18:18:33.488185+00:00 app[web.1]: ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-01-03T18:18:33.488185+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/gunicorn/util.py", line 359, in import_app
2025-01-03T18:18:33.488185+00:00 app[web.1]: mod = importlib.import_module(module)
2025-01-03T18:18:33.488186+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-01-03T18:18:33.488186+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2025-01-03T18:18:33.488186+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-03T18:18:33.488186+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-01-03T18:18:33.488187+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-01-03T18:18:33.488187+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
2025-01-03T18:18:33.488187+00:00 app[web.1]: ModuleNotFoundError: No module named 'PersonalWebsite.wsgi'
2025-01-03T18:18:33.488233+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [9] [INFO] Worker exiting (pid: 9)
2025-01-03T18:18:33.516644+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [2] [INFO] Shutting down: Master
2025-01-03T18:18:33.516668+00:00 app[web.1]: [2025-01-03 18:18:33 +0000] [2] [INFO] Reason: Worker failed to boot.
2025-01-03T18:18:33.583417+00:00 heroku[web.1]: Process exited with status 3
2025-01-03T18:18:33.601857+00:00 heroku[web.1]: State changed from starting to crashed
2025-01-03T18:18:53.607178+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=f5868e22-941e-44ee-8fb6-c40af01b7f25 fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
2025-01-03T18:18:53.726808+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=peresonal-website-a6e4a5ee3146.herokuapp.com request_id=ad83f09c-abb1-46e5-bf7f-f0d404281d64 fwd="84.216.183.65" dyno= connect= service= status=503 bytes= protocol=https
